export interface FurnitureCatalogItem {
    id: string;
    name: string;
    category: string;
    subtitle: string;
    imageUrl: string;
    defaultLength: number;
    defaultWidth: number;
    defaultHeight: number;
}

export const FURNITURE_CATALOG: FurnitureCatalogItem[] = [
    {
        id: "sofa-1",
        name: "Sofa",
        category: "Living Room",
        subtitle: "Bespoke handcrafted sofas",
        imageUrl: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=800",
        defaultLength: 7.0,
        defaultWidth: 3.0,
        defaultHeight: 2.8,
    },
    {
        id: "dining-table-1",
        name: "Dining Table",
        category: "Dining Room",
        subtitle: "Hand-turned solid wood dining tables",
        imageUrl: "https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?auto=format&fit=crop&q=80&w=800",
        defaultLength: 6.0,
        defaultWidth: 3.5,
        defaultHeight: 2.5,
    },
    {
        id: "study-table-1",
        name: "Study Table",
        category: "Office & Study",
        subtitle: "Ergonomic wooden study tables",
        imageUrl: "https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&q=80&w=800",
        defaultLength: 4.5,
        defaultWidth: 2.5,
        defaultHeight: 2.5,
    },
    {
        id: "bed-1",
        name: "Bed",
        category: "Bedroom",
        subtitle: "Sturdy solid wood beds",
        imageUrl: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&q=80&w=800",
        defaultLength: 6.5,
        defaultWidth: 6.0,
        defaultHeight: 3.5,
    },
    {
        id: "wardrobe-1",
        name: "Wardrobe",
        category: "Bedroom Storage",
        subtitle: "Spacious wooden wardrobes",
        imageUrl: "https://images.unsplash.com/photo-1558997519-83ea9252edf8?auto=format&fit=crop&q=80&w=800",
        defaultLength: 4.0,
        defaultWidth: 2.0,
        defaultHeight: 7.0,
    },
    {
        id: "coffee-table-1",
        name: "Coffee Table",
        category: "Living Room",
        subtitle: "Elegant living room coffee tables",
        imageUrl: "https://images.unsplash.com/photo-1533090161767-e6ffed986c88?auto=format&fit=crop&q=80&w=800",
        defaultLength: 4.0,
        defaultWidth: 2.0,
        defaultHeight: 1.5,
    },
    {
        id: "chair-1",
        name: "Chair",
        category: "Seating",
        subtitle: "Comfortable and durable wooden chairs",
        imageUrl: "https://images.unsplash.com/photo-1580481077194-44243689ad5d?auto=format&fit=crop&q=80&w=800",
        defaultLength: 1.8,
        defaultWidth: 1.8,
        defaultHeight: 3.2,
    },
    {
        id: "bookshelf-1",
        name: "Bookshelf",
        category: "Living & Study Storage",
        subtitle: "Classic wooden bookshelves",
        imageUrl: "https://images.unsplash.com/photo-1594980596870-8aa52a78d8cd?auto=format&fit=crop&q=80&w=800",
        defaultLength: 3.5,
        defaultWidth: 1.2,
        defaultHeight: 6.0,
    },
    {
        id: "dressing-table-1",
        name: "Dressing Table",
        category: "Bedroom",
        subtitle: "Intricately designed dressing tables",
        imageUrl: "https://images.unsplash.com/photo-1595428774223-ef52624120d2?auto=format&fit=crop&q=80&w=800",
        defaultLength: 3.5,
        defaultWidth: 1.8,
        defaultHeight: 5.5,
    },
    {
        id: "shoe-rack-1",
        name: "Shoe Rack",
        category: "Entryway & Storage",
        subtitle: "Organized wooden shoe racks",
        imageUrl: "https://images.unsplash.com/photo-1540574163026-643ea20ade25?auto=format&fit=crop&q=80&w=800",
        defaultLength: 3.0,
        defaultWidth: 1.2,
        defaultHeight: 3.0,
    },
    {
        id: "tv-unit-1",
        name: "TV Unit / Cabinet",
        category: "Living Room",
        subtitle: "Modern and traditional TV units",
        imageUrl: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&q=80&w=800",
        defaultLength: 5.5,
        defaultWidth: 1.5,
        defaultHeight: 2.0,
    },
    {
        id: "side-table-1",
        name: "Side Table",
        category: "Living Room",
        subtitle: "Compact wooden side tables",
        imageUrl: "https://images.unsplash.com/photo-1532372320572-cda25653a26d?auto=format&fit=crop&q=80&w=800",
        defaultLength: 1.8,
        defaultWidth: 1.8,
        defaultHeight: 2.0,
    },
    {
        id: "home-temple-1",
        name: "Home Temple (Mandir)",
        category: "Pooja Room",
        subtitle: "Heritage carved wooden mandirs",
        imageUrl: "https://images.unsplash.com/photo-1609766857041-ed402ea8069a?auto=format&fit=crop&q=80&w=800",
        defaultLength: 3.0,
        defaultWidth: 1.8,
        defaultHeight: 4.5,
    },
    {
        id: "wooden-bench-1",
        name: "Wooden Bench",
        category: "Seating",
        subtitle: "Rustic wooden seating benches",
        imageUrl: "https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?auto=format&fit=crop&q=80&w=800",
        defaultLength: 4.5,
        defaultWidth: 1.5,
        defaultHeight: 1.6,
    },
    {
        id: "crockery-cabinet-1",
        name: "Crockery Cabinet",
        category: "Dining Storage",
        subtitle: "Elegant glass and wood crockery units",
        imageUrl: "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&q=80&w=800",
        defaultLength: 3.5,
        defaultWidth: 1.5,
        defaultHeight: 6.0,
    },
    {
        id: "indoor-swing-1",
        name: "Indoor Swing (Jhula)",
        category: "Living Room Heritage",
        subtitle: "Traditional carved wooden jhulas",
        imageUrl: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&q=80&w=800",
        defaultLength: 5.0,
        defaultWidth: 2.5,
        defaultHeight: 6.5,
    },
    {
        id: "chest-of-drawers-1",
        name: "Chest of Drawers",
        category: "Storage",
        subtitle: "Versatile wooden chests of drawers",
        imageUrl: "https://images.unsplash.com/photo-1538688525198-9b88f6f53126?auto=format&fit=crop&q=80&w=800",
        defaultLength: 3.2,
        defaultWidth: 1.6,
        defaultHeight: 3.8,
    },
    {
        id: "bar-cabinet-1",
        name: "Bar Cabinet",
        category: "Dining & Bar",
        subtitle: "Stylish wooden bar cabinets",
        imageUrl: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&q=80&w=800",
        defaultLength: 3.5,
        defaultWidth: 1.8,
        defaultHeight: 4.2,
    },
    {
        id: "console-table-1",
        name: "Console Table",
        category: "Entryway & Living",
        subtitle: "Decorative wooden console tables",
        imageUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=800",
        defaultLength: 4.0,
        defaultWidth: 1.2,
        defaultHeight: 2.8,
    },
    {
        id: "bedside-table-1",
        name: "Bedside Table",
        category: "Bedroom",
        subtitle: "Minimalist solid wood nightstands",
        imageUrl: "https://images.unsplash.com/photo-1532372576444-dda954194ad0?auto=format&fit=crop&q=80&w=800",
        defaultLength: 1.6,
        defaultWidth: 1.4,
        defaultHeight: 1.8,
    },
];